### ISSUE TITLE
"Unexpected API error. KeyError: com.github.brpaz.ulauncher-text-expander"

### ISSUE THREAD

**Issue by cecoates** [brpaz/ulauncher-text-expander#2]
Love the concept, and looking forward to using it. But when I tried to adjust the settings, such as the keyword or snippet directory, the above error displays.

From the log:

`2018-10-06 12:07:53,992 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_get_all() | API call /get/all
2018-10-06 12:07:55,174 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_extension_get_all() | Handling /extension/get-all
2018-10-06 12:08:03,877 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_extension_update_prefs() | Update extension preferences: {'callback': '__jp2', 'id': 'com.github.brpaz.ulauncher-text-expander', 'pref.kw': 'tex', 'pref.expansions_dir': ''}
2018-10-06 12:08:03,877 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | Unexpected API error. KeyError: com.github.brpaz.ulauncher-text-expander
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 160, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python2.7/dist-packages/ulauncher/util/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 368, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python2.7/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-text-expander'`

I'm also unable to find/add any snippets, unsure if it's related to the above.

Ulauncher installed via  ulauncher_4.3.1.r4_all.deb, text-expander installed (on different attempts) via the uLauncher settings as well as downloading directly from GitHub and copying it to the expansions directory. Pop!_OS 18.04 (based on Ubuntu 18.04).

**Comment by cecoates** [comment]
After reading a reply to a similar error issue for:

https://github.com/brpaz/ulauncher-lipsum

I did a bit more experimentation, and it turns out some of the Python modules this extension requires aren't installed by default (so those of us who have freshly installed Python won't have them.)

Once I installed glob2 and logger, then restarted Ulauncher, it worked like a charm.
